version: "3"

dotenv: [".env"]

includes:
  client: ./task/Client-Taskfile.yaml
  user: ./task/User-Taskfile.yaml

tasks:
  deploy:
    requires:
      vars:
        - AWS_STAGE
        - LOG_LEVEL
        - CIRROSTRATUS_OAUTH2_MODULE_NAME
        - CIRROSTRATUS_OUTH2_USER_TABLE
        - AWS_DEFAULT_REGION
        - AWS_REGION
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - USER_MIN_PASSWORD_LENGTH
        - USER_UPPER_CASE_REQUIRED
        - USER_LOWER_CASE_REQUIRED
        - USER_NUMBER_REQUIRED
        - USER_SPECIAL_CHARACTER_REQUIRED
    deps:
      - client:build
      - user:build
    cmds:
      - |
        cd ./terragrunt
        terragrunt run-all apply --terragrunt-non-interactive
        cd ..
  undeploy:
    cmds:
      - |
        cd ./terragrunt
        terragrunt run-all destroy --terragrunt-non-interactive
        cd ..
  output:
    cmds:
      - |
        cd ./terragrunt
        terragrunt run-all output --terragrunt-non-interactive
        cd ..
