version: "3"
env:
  AWS_STAGE: prod
  LOG_LEVEL: INFO
tasks:
  client:
    deps:
      - build
    env:
      AWS_STAGE: local
      LOG_LEVEL: DEBUG
    cmds:
      - ./bin/client/bootstrap
  clean:
    cmds:
      - rm -rf ./bin ./dist
  build:
    deps:
      - clean
    env:
      GOARCH: amd64
      GOOS: linux
      CGO_ENABLED: 0
    cmds:
      - |
        mkdir -p ./bin/client ./dist/client ./bin/user ./dist/user
        go build -ldflags="-s -w" -tags lambda.norpc -o ./bin/client/bootstrap ./client
        go build -ldflags="-s -w" -tags lambda.norpc -o ./bin/user/bootstrap ./user
  deploy:
    deps:
      - build
    cmds:
      - |
        cd ./terragrunt
        terragrunt run-all apply --terragrunt-non-interactive
        cd ..
  undeploy:
    cmds:
      - |
        cd ./terragrunt
        terragrunt run-all destroy --terragrunt-non-interactive
        cd ..
  output:
    cmds:
      - |
        cd ./terragrunt
        terragrunt run-all output --terragrunt-non-interactive
        cd ..